//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class idx_equityEntities : DbContext
    {
        public idx_equityEntities()
            : base("name=idx_equityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equity_holding> equity_holding { get; set; }
        public virtual DbSet<financial> financials { get; set; }
        public virtual DbSet<fundamental> fundamentals { get; set; }
        public virtual DbSet<sector> sectors { get; set; }
        public virtual DbSet<stock_quotes> stock_quotes { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<total_composition> total_composition { get; set; }
        public virtual DbSet<broker> brokers { get; set; }
        public virtual DbSet<portfolio> portfolios { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
    }
}
