//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class equity_holding
    {
        public long Id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Domestic_Insurance { get; set; }
        public Nullable<decimal> Domestic_Company { get; set; }
        public Nullable<decimal> Domestic_Pension_Fund { get; set; }
        public Nullable<decimal> Domestic_Bank { get; set; }
        public Nullable<decimal> Domestic_Individual { get; set; }
        public Nullable<decimal> Domestic_Mutual_Fund { get; set; }
        public Nullable<decimal> Domestic_Security { get; set; }
        public Nullable<decimal> Domestic_Foundation { get; set; }
        public Nullable<decimal> Domestic_Others { get; set; }
        public Nullable<decimal> Foreign_Insurance { get; set; }
        public Nullable<decimal> Foreign_Company { get; set; }
        public Nullable<decimal> Foreign_Pension_Fund { get; set; }
        public Nullable<decimal> Foreign_Bank { get; set; }
        public Nullable<decimal> Foreign_Individual { get; set; }
        public Nullable<decimal> Foreign_Mutual_Fund { get; set; }
        public Nullable<decimal> Foreign_Security { get; set; }
        public Nullable<decimal> Foreign_Foundation { get; set; }
        public Nullable<decimal> Foreign_Others { get; set; }
    
        public virtual stock stock { get; set; }
    }
}
