//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fundamental
    {
        public int id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<decimal> return_on_equity { get; set; }
        public Nullable<decimal> return_on_asset { get; set; }
        public Nullable<decimal> gross_profit_margin { get; set; }
        public Nullable<decimal> operating_profit_margin { get; set; }
        public Nullable<decimal> net_profit_margin { get; set; }
        public Nullable<decimal> debt_equity_ratio { get; set; }
        public Nullable<decimal> earning_per_share { get; set; }
        public Nullable<decimal> cash_flow_per_share { get; set; }
        public Nullable<decimal> book_value_per_share { get; set; }
        public Nullable<decimal> shares_amount_issued { get; set; }
    
        public virtual stock stock { get; set; }
    }
}
