//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_composition
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public string code { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> Domestic_Total { get; set; }
        public Nullable<decimal> Foreign_Total { get; set; }
    }
}
